version: '3'

services:
  db:
    image: mysql:5.7
    restart: always
    container_name: db
    environment:
      MYSQL_DATABASE: booking_portal
      MYSQL_ALLOW_EMPTY_PASSWORD: 1
    ports:
      - 3306:3306
    networks:
      - app
    logging:
      driver: awslogs
      options:
        awslogs-group: bookingportal-db
        awslogs-region: us-west-1
        awslogs-stream-prefix: db

  app:
    image: michelledhuang/booking-portal:1.3
    environment:
      MYSQL_HOST: db
    ports:
      - 3003:3003
    depends_on:
      - db
    logging:
      driver: awslogs
      options:
        awslogs-group: bookingportal-app
        awslogs-region: us-west-1
        awslogs-stream-prefix: app
